[tool.poetry]
name = "xiudong-selenium"
version = "0.1.0"
description = ""
authors = ["Sakura <1467649772@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
